---
kind: pipeline
type: docker
name: automation-station weekly build

steps:
  - name: clone and fetch version file
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      GIT_CLONE_PAT:
        from_secret: git_clone_pat
    settings:
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/development
      playbook: .ansible/clone_and_fetch.yaml
      private_key:
        from_secret: automation_id_rsa


  - name: debug
    image: bash
    commands:
      - ls -al
      - cat ProjectVersion.txt
      - export FOO=BAR


  - name: debug 2
    image: bash
    environment:
      -FOO
    commands:
      - printenv FOO
      - printenv


  - name: parse version
    image: jlordiales/jyparser
    commands:
      - ls -al
      - /bin/start ProjectVersion.txt get ".m_EditorVersion"
      - /bin/start ProjectVersion.txt get ".m_EditorVersionWithRevision"

trigger:
  event:
    - push
  branch:
    - development

...
