---
kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      GIT_CLONE_PAT:
        from_secret: git_clone_pat
    settings:
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/development
      playbook: .ansible/build.yaml
      private_key:
        from_secret: automation_id_rsa
        
trigger:
  event:
    - push
  branch:
    - development

...
