---
kind: pipeline
type: docker
name: automation-station weekly build

concurrency:
  limit: 1

steps:
  - name: build
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      GIT_CLONE_PAT:
        from_secret: git_clone_pat
      BUTLER_API_KEY:
        from_secret: butler_api_key
      NEXUS_PASS:
        from_secret: nexus_pass
    settings:
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/development
      playbook: .ansible/build.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password


trigger:
  event:
    - push
  branch:
    - development

...
