---
kind: pipeline
type: docker
name: automation-station weekly build

steps:
  - name: build
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      GIT_CLONE_PAT:
        from_secret: git_clone_pat
      NEXUS_PASS:
        from_secret: nexus_pass
      NEXUS_USER:
        from_secret: nexus_user
    settings:
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/development
      playbook: .ansible/build.yaml
      private_key:
        from_secret: automation_id_rsa

trigger:
  event:
    - push
  branch:
    - development

...
