- hosts: drone
  gather_facts: no
  connection: local
  tasks:
    
    - name: boot vm
      proxmox_kvm:
        vmid: '{{ proxmox_vm_id }}'
        name: '{{ proxmox_vm_name }}'
        api_user: '{{ proxmox_user }}'
        api_password: '{{ proxmox_api_password }}'
        api_host: '{{ proxmox_api_host }}'
        node: '{{ proxmox_node }}'
        state: started
