- hosts: manager
  roles:
    - common

  tasks:

    - include_role:
        name: common
        tasks_from: make_config_dir

    - include_role:
        name: common
        tasks_from: make_data_dir
    
    
    - name: Git clone modulocity/automation-station
      git:
        repo: 'https://{{ git_clone_pat }}@github.com/modulocity/automation-station.git'
        dest: '{{ config_dir }}/automation-station'
        version: development
        accept_hostkey: yes
        update: yes

    - name: fetch the ProjectVersion.txt file
      fetch:
        src: '{{ config_dir }}/automation-station/ProjectSettings/ProjectVersion.txt'
        dest: '{{ playbook_dir }}'
        flat: yes

    # - name: Load version from ProjectVersion.txt
    #   include_vars:
    #     file: '{{ playbook_dir }}/../ProjectVersion.yaml'

    # - debug:
    #     msg: 'm_EditorVersion: {{ m_EditorVersion }}'

    # - debug:
    #     msg: 'm_EditorVersionWithRevision: {{ m_EditorVersionWithRevision }}'
