- hosts: manager
  roles:
    - common

  tasks:

    - include_role:
        name: common
        tasks_from: make_config_dir


    - include_role:
        name: common
        tasks_from: make_data_dir
    

    - name: git clone modulocity/automation-station
      git:
        repo: 'https://{{ git_clone_pat }}@github.com/modulocity/automation-station.git'
        dest: '{{ config_dir }}/automation-station'
        depth: 1
        version: development
        accept_hostkey: yes
        update: yes


    - name: git clone game-ci/docker
      git:
        repo: 'https://github.com/game-ci/docker.git'
        dest: '{{ config_dir }}/game-ci'
        depth: 1
        version: main
        accept_hostkey: yes
        update: yes


    - name: fetch the ProjectVersion.txt file
      fetch:
        src: '{{ config_dir }}/automation-station/ProjectSettings/ProjectVersion.txt'
        dest: '{{ playbook_dir }}/../'
        flat: yes

    - name: Load version from ProjectVersion.txt
      include_vars:
        file: '{{ playbook_dir }}/../ProjectVersion.txt'

    - name: extract variables
      set_fact:
        version: "{{ m_EditorVersionWithRevision.stdout.split(' ') | first }}"
        changeset: "{{ m_EditorVersionWithRevision.stdout.split(' ') | last | replace('(','') | replace(')','') | replace('\n','') }}"

    - debug:
        msg: "version: {{ version }}"

    - debug:
        msg: "changeset: {{ changeset }}"





